name = "nutriweb"
type = "javascript"   # tipo de Worker, puede ser "javascript" o "webpack" si usas bundler
account_id = "<TU_ACCOUNT_ID>"
workers_dev = true
compatibility_date = "2025-11-19"

# Opcional: si quieres publicar en un dominio personalizado
# route = "https://nutri-web.eliasaraujo.org/*"
# zone_id = "<TU_ZONE_ID>"

# Configuración de assets estáticos (HTML, CSS, JS)
[site]
bucket = "./public"   # carpeta donde guardas index.html, style.css, main.js
entry-point = "workers-site"
